# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vnstock.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'vnstock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvnstock.proto\x12\x07vnstock\"|\n\x0cStockRequest\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n\nstart_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n\x08\x65nd_date\x18\x04 \x01(\tR\x07\x65ndDate\x12\x1a\n\x08interval\x18\x05 \x01(\tR\x08interval\"\x83\x02\n\rStockResponse\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x34\n\x0bmarket_data\x18\x03 \x01(\x0b\x32\x13.vnstock.MarketDataR\nmarketData\x12\x37\n\rprice_history\x18\x04 \x03(\x0b\x32\x12.vnstock.PriceDataR\x0cpriceHistory\x12\x1f\n\x0b\x64\x61ta_points\x18\x05 \x01(\x05R\ndataPoints\x12\x16\n\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n\x05\x65rror\x18\x07 \x01(\tR\x05\x65rror\"\x9c\x02\n\nMarketData\x12!\n\x0clatest_price\x18\x01 \x01(\x01R\x0blatestPrice\x12!\n\x0cprice_change\x18\x02 \x01(\x01R\x0bpriceChange\x12\x30\n\x14price_change_percent\x18\x03 \x01(\x01R\x12priceChangePercent\x12%\n\x0e\x63urrent_volume\x18\x04 \x01(\x03R\rcurrentVolume\x12!\n\x0cvolume_ratio\x18\x05 \x01(\x01R\x0bvolumeRatio\x12)\n\x10price_volatility\x18\x06 \x01(\x01R\x0fpriceVolatility\x12!\n\x0ctrading_date\x18\x07 \x01(\tR\x0btradingDate\"s\n\tPriceData\x12\x12\n\x04\x64\x61te\x18\x01 \x01(\tR\x04\x64\x61te\x12\x14\n\x05\x63lose\x18\x02 \x01(\x01R\x05\x63lose\x12\x16\n\x06volume\x18\x03 \x01(\x03R\x06volume\x12\x12\n\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n\x03low\x18\x05 \x01(\x01R\x03low2Q\n\x10StockDataService\x12=\n\x0cGetStockData\x12\x15.vnstock.StockRequest\x1a\x16.vnstock.StockResponseB&Z$../bot-trade/pkg/grpc-broker/vnstockb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vnstock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$../bot-trade/pkg/grpc-broker/vnstock'
  _globals['_STOCKREQUEST']._serialized_start=26
  _globals['_STOCKREQUEST']._serialized_end=150
  _globals['_STOCKRESPONSE']._serialized_start=153
  _globals['_STOCKRESPONSE']._serialized_end=412
  _globals['_MARKETDATA']._serialized_start=415
  _globals['_MARKETDATA']._serialized_end=699
  _globals['_PRICEDATA']._serialized_start=701
  _globals['_PRICEDATA']._serialized_end=816
  _globals['_STOCKDATASERVICE']._serialized_start=818
  _globals['_STOCKDATASERVICE']._serialized_end=899
# @@protoc_insertion_point(module_scope)
